backend/accounts/urls.py
from django.urls import path

from .views import dashboard, patient_identity, patient_search

app_name = "accounts"

urlpatterns = [
    path('', dashboard, name="dashboard"),
    path('patient/<int:pk>/identity/', patient_identity, name='patient_identity'),
    path('patient/rechercher/', patient_search, name="patient_search"),
]

### Recherche Patient
# patient/recherche?q=XXX
# patient/recherche_insi?q=XXX

backend/backend/urls.py
from django.contrib.auth.views import LoginView, logout_then_login
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('se-connecter/', LoginView.as_view(), name='login'),
    path('se-deconnecter/', logout_then_login, name='logout'),
    path('', include('accounts.urls', namespace="accounts")),
]

backend/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.shortcuts import reverse
from django.db import models


import datetime, json, requests

CIV_CHOICES = [
    ("I", "Indéterminé"),
    ("F", "Féminin"),
    ("M", "Masculin"),
]

STATUT_CHOICES = [
    ("P", "Provisoire"),
    ("R", "Récupérée"),
    ("V", "Vérifiée"),
    ("Q", "Qualifiée")
]

STATUT_COMPL_CHOICES = [
    ("H", "Homonyme"),
    ("F", "Fictive"),
    ("D", "Douteuse"),
]

TYPE_CONTACT_CHOICES = [
    ("PR", "Parent"),
    ("FR", "Fratrie"),
    ("PA", "Partenaire"),
    ("PC", "Proche de confiance")
]

GROUPE_SANGUIN_CHOICES = [
    ("O", "O"),
    ("A", "A"),
    ("B", "B"),
    ("AB", "AB"),
]

RHESUS_SANGUIN_CHOICES = [
    ("-", "-"),
    ("+", "+"),
]

class Utilisateur(AbstractUser):
    pass

class Patient(models.Model):
    statut = models.CharField(max_length=1, choices=STATUT_CHOICES, verbose_name="Statut d'identité")
    statut_compl = models.CharField(max_length=1, choices=STATUT_COMPL_CHOICES, blank=True, verbose_name="Statut d'identité complémentaire")
    ins = models.CharField(max_length=15, verbose_name="Matricule INS")
    oid = models.CharField(max_length=20, verbose_name="Object identifier")
    # Identité primaire
    civilite = models.CharField(max_length=2, choices=CIV_CHOICES, verbose_name="civilité")
    birth_lname = models.CharField(max_length=100, verbose_name="Nom de naissance")
    birth_fnames = models.CharField(max_length=100, verbose_name="Prénom(s) de naissance")
    birth_fname = models.CharField(max_length=100, verbose_name="Premier prénom de naissance")
    birth_date = models.DateField(verbose_name="Date de naissance")
    birth_insee = models.CharField(max_length=5, verbose_name="Commune de naissance - code INSEE")
    # Identité secondaire
    used_fname = models.CharField(max_length=100, verbose_name="Prénom utilisé")
    used_lname = models.CharField(max_length=100, verbose_name="Nom utilisé")
    # Adresse
    adresse_line = models.CharField(max_length=200, blank=True, verbose_name="Adresse Ligne")
    adresse_zipc = models.CharField(max_length=5, blank=True, verbose_name="Code postal")
    adresse_city = models.CharField(max_length=100, blank=True, verbose_name="Ville")
    adresse_pays = models.CharField(max_length=50, blank=True, verbose_name="Pays")
    # Telephone
    phone_fixe = models.CharField(max_length=20, blank=True, verbose_name="Téléphone fixe")
    phone_port = models.CharField(max_length=20, blank=True, verbose_name="Téléphone portable")
    # Contact urgence
    contact1_lname = models.CharField(max_length=100, blank=True, verbose_name="Nom du contact 1")
    contact1_fname = models.CharField(max_length=100, blank=True, verbose_name="Prénom du contact 1")
    contact1_phone_fixe = models.CharField(max_length=12, blank=True, verbose_name="Téléphone fixe du contact 1")
    contact1_phone_port = models.CharField(max_length=20, blank=True, verbose_name="Téléphone portable du contact 1")
    contact1_relation = models.CharField(max_length=2, blank=True, choices=TYPE_CONTACT_CHOICES, verbose_name="Relation du contact 1")
    contact2_lname = models.CharField(max_length=100, blank=True, verbose_name="Nom du contact 2")
    contact2_fname = models.CharField(max_length=100, blank=True, verbose_name="Prénom du contact 2")
    contact2_phone_fixe = models.CharField(max_length=20, blank=True, verbose_name="Téléphone fixe du contact 2")
    contact2_phone_port = models.CharField(max_length=20, blank=True, verbose_name="Téléphone portable du contact 2")
    contact2_relation = models.CharField(max_length=2, choices=TYPE_CONTACT_CHOICES, blank=True, verbose_name="Relation du contact 2")
    # Données de santé
    groupe_sanguin = models.CharField(max_length=2, blank=True, choices=GROUPE_SANGUIN_CHOICES, verbose_name="Groupe Sanguin")
    rhesus_sanguin = models.CharField(max_length=2, blank=True, choices=RHESUS_SANGUIN_CHOICES, verbose_name="Rhésus Sanguin")

    def get_absolute_url(self):
        return reverse("accounts:patient_identity", kwargs={"pk": self.pk})
    
    def get_age(self):
        today = datetime.datetime.now()
        diff = abs((today-self.birth_date))
        return diff

    def get_commune(self):
        # FIXME Temporary solution => Urgent fixe
        cities_json = requests.get("http://127.0.0.1:8000/static/utils/commune2021.json").json()
        cities_name = [x for x in cities_json if x['INSEE'] == str(self.birth_insee)]
        return cities_name[0].get("Nom").upper()

    def __str__(self):
        return "{} {} - Né le {}".format(self.birth_lname.upper(), self.birth_fnames, self.birth_date.strftime("%d %B %Y"))

    class Meta:
        permissions = [
            ("can_change_qualify_identity", "Can change qualify identity"),
            ("can_set_statut_provisoire", "Can set identities status to temporary"),
            ("can_view_detail_patient", "Can view patient detail"),
        ]

backend/accounts/views.py
from django.contrib.auth.decorators import permission_required, login_required
from django.shortcuts import get_list_or_404, render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Q

import reversion

from .models import Patient

@login_required
def dashboard(request):
    context = {}
    return render(request, 'dashboard.html', context)

@permission_required("accounts.can_set_statut_provisoire")
def all_patient_to_provisoire(request):
    with reversion.create_revision():
        # Updates made on object
        obj = Patient.objects.all()
        obj.update(statut="P")
        # Revision meta data
        reversion.set_user(request.user)
        reversion.set_comment("Downgrade all patient identity to PROVISOIRE")
    return HttpResponse("Vous avez défini le statut de toutes les identités en &laquo; PROVISOIRE &raquo;")

@permission_required("accounts.can_view_patient")
def patient_search(request):
    birth_lname = request.GET.get("birth_lname")
    birth_fname = request.GET.get("birth_fname")
    ins = request.GET.get("ins")

    if birth_fname == None: birth_fname = ""
    if birth_lname == None: birth_lname = ""
    if ins == None: ins = ""
    results = Patient.objects.filter(ins__iexact=ins)
    results |= Patient.objects.filter(birth_fnames__iexact=birth_fname)
    results |= Patient.objects.filter(birth_lname__iexact=birth_lname)
    context = {"results": results}
    return render(request, 'patient/patient_search.html', context)

@permission_required("accounts.can_view_detail_patient")
def patient_identity(request, pk):
    context = {"patient": get_object_or_404(Patient, pk=pk)}
    return render(request, "patient/patient_identity.html", context=context)

def patient_agenda(request, pk):
    context = {"patient": get_object_or_404(Patient, pk=pk)}
    return render(request, "patient/patient_agenda.html", context=context)

def patient_health_data(request, pk):
    context = {"patient": get_object_or_404(Patient, pk=pk)}
    return render(request, "patient/patient_health_data.html", context=context)

def patient_acces_permissions(request, pk):
    context = {"patient": get_object_or_404(Patient, pk=pk)}
    return render(request, "patient/patient_acces_permissions.html", context=context)

def patient_health_data_urgence(request, pk):
    context = {"patient": get_object_or_404(Patient, pk=pk)}
    return HttpResponse("Accès d'urgence aux données de santé après validation et enregistrement de l'accès et du motif d'accès")

def patient_delete(request, pk):
    patient = get_object_or_404(Patient, pk=pk)
    # using reversion (delete revision and version)
    # To be reverted, we have to store the primary key in a file to be able to retrieve these identity
    patient.delete()
    return HttpResponse("Vous avez supprimé le patient")

backend/accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block base_content %}
{% include 'includes/_navbar.html' %}
{% block content %}
<div class="container mt-3">
  Tableau de bord
</div>
{% endblock content %}

{% endblock base_content %}

backend/accounts/templates/patient/patient_identity.html
{% extends "dashboard.html" %}

{%  block content %}
<div class="container mt-3">
    <ul>
        <li><strong>Statut :</strong> {{patient.get_statut_display}} - {{patient.get_statut_compl_display}}</li>
        <li><strong>Civilité :</strong> {{patient.get_civilite_display}}</li>
        <li><strong>Nom de naissance :</strong> {{patient.birth_lname}}</li>
        <li><strong>Prénom(s) de naissance :</strong> {{patient.birth_fnames}}</li>
        <li><strong>Date de Naissance :</strong> {{patient.birth_date}}</li>
        <li><strong>Commune de naissance (Code INSEE) :</strong> {{patient.get_commune}} ({{patient.birth_insee}})</li>
        <li><strong>Nom utilisé :</strong> {{patient.used_lname}}</li>
        <li><strong>Prénom utilisé :</strong> {{patient.used_fname}}</li>
    </ul>
</div>
{% endblock content %}

backend/accounts/templates/patient/patient_search.html
{% extends 'dashboard.html' %}

{% block content %}
<div class="container mt-3">
    <form action="" method="get">
        <div class="row">
            <div class="col-3 mb-3">
                <label for="ins">Matricule INS</label>
                <input type="text" name="ins" id="ins" class="form-control">
            </div>

            <div class="col-3 mb-3">
                <label for="birth_lname">Nom de naissance</label>
                <input type="text" name="birth_lname" class="form-control">
            </div>
            <div class="col-3 mb-3">
                <label for="birth_fname">Prénom(s) de naissance</label>
                <input type="text" name="birth_fname" id="birth_fname" class="form-control">
            </div>
            <div class="col-3 mb-3 my-auto">
                <button class="btn btn-primary w-100">Rechercher</button>
            </div>
        </div>
        <hr>
        Résultats de recherche
        <ul>

        
        {% for res in results %}
        <li><a href="{{res.get_absolute_url}}">{{res}}</a></li>
        {% endfor %}
        </ul>
    </form>
</div>

{% endblock content %}

backend/templates/base.html
<!doctype html>
<html lang="fr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

    <title>HMS - NAME</title>
  </head>
  <body>
    {% block base_content %}
    {% endblock base_content %}

    <!-- Optional JavaScript; choose one of the two! -->
    
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

backend/templates/includes/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">NAME</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Tableau de bord</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:patient_search' %}">Patients</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        {{user}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">My profile</a></li>
                        {% if user.is_staff %}
                        <li><a class="dropdown-item text-danger" href="{% url 'admin:index' %}">Administration</a></li>
                        {% endif %}
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Se déconnecter</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>